# src/main/resources/application-test.yaml

# --- Test Profile Configuration ---
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS staging
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  sql:
    init:
      mode: always  # Replaces deprecated 'initialization-mode'

  # H2 console configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: staging

  test:
    database:
      replace: none

logging:
  level:
    org.springframework.test: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE