# src/main/resources/application-dev.yaml

# --- Development Profile Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgresuser
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    image: redis:latest
    container_name: my-redis
    ports: "6379:6379"
    volumes: redis-data:/data
    restart: unless-stopped

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
