--Code generated by pgAdmin through the GUI

-- Table: staging.lifestyle_deposits

-- DROP TABLE IF EXISTS staging.lifestyle_deposits;

CREATE TABLE IF NOT EXISTS staging.lifestyle_deposits
(
    id integer NOT NULL,
    lifestyle_type character varying(20)[] COLLATE pg_catalog."default" NOT NULL,
    monthly_deposit numeric(10,2)[] NOT NULL,
    annual_expenses numeric(12,2)[] NOT NULL,
    CONSTRAINT lifestyle_deposits_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS staging.lifestyle_deposits
    OWNER to postgresuser;